name: Build and Publish

on:
  push:
    branches: [ "main", "dev" ] 
  pull_request:
    branches: [ "main", "dev" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests with Maven
        run: mvn --batch-mode verify --file ShopVerse-Producto/pom.xml

      - name: Display test results
        if: failure()
        run: |
          echo "==== TEST FAILURES ===="
          find ShopVerse-Producto/target/surefire-reports -name '*.txt' -exec cat {} +
